
# linear regression from scratch using pytorch
> A quick glance at how to create linear regression
- toc: true
- branch: master
- badges: true
- comments: true
- categories: [beginner]

In [ ]:
import numpy as np
import torch

In [60]:
inputs = np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70]
], dtype= 'float32')

In [61]:
targets = np.array([
    [56, 70],
    [81, 101],
    [119, 133],
    [22, 37],
    [103, 119]
], dtype= 'float32')

In [62]:
# converting inputs and targets into tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print (inputs)
print (targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


The first row of w and the first element of b are used to predict the first target variable i.e. yield of apples, and similarly the second for oranges.

In [64]:
# weights and biases
w = torch.randn(2, 3, requires_grad = True)
b = torch.randn(2, requires_grad= True)

In [65]:
print (w, b)
# torch.randn creates tensor with elements mean = 0 and standard_deviation = 1

tensor([[-0.5616,  0.8701,  1.3327],
        [-0.8417,  1.6244,  0.2163]], requires_grad=True) tensor([-0.3904,  1.0251], requires_grad=True)


In [66]:
# pred  = x * w + b

In [67]:
def model(x):
    return x @ w.t() + b
# @ : dot_product
# .t(): takes transpose

In [68]:
# Generaten Predictions
preds = model(inputs)

In [69]:
print (preds, targets)

tensor([[ 74.2108,  57.7131],
        [110.3599,  81.2160],
        [144.6323, 158.0064],
        [ 29.0453,  -6.9796],
        [137.6730, 114.0266]], grad_fn=<AddBackward0>) tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


loss function
Mean_square error algorithm

   * Calculate the difference between the two matrices (preds and targets).
   * Square all elements of the difference matrix to remove negative values.
   * Calculate the average of the elements in the resulting matrix.


In [71]:
def mse(t1, t2):
    diff = t1-t2
    return torch.sum(diff*diff)/ diff.numel()
# diff*diff : element wise multiplication

In [72]:
# compute_loss
loss = mse(preds, targets)
print (loss)

tensor(622.9136, grad_fn=<DivBackward0>)


In [73]:
# computing gradients
loss.backward(retain_graph=True)

In [74]:
print (w)
print (w.grad)

tensor([[-0.5616,  0.8701,  1.3327],
        [-0.8417,  1.6244,  0.2163]], requires_grad=True)
tensor([[ 1868.4410,  2174.0151,  1367.3108],
        [-1070.1625,  -316.3842,  -463.9043]])


In [75]:
w.grad.zero_()
b.grad.zero_()
print (w.grad, b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([0., 0.])


Gradient Descent Alogrithm:
    * Generate predictions

    * Calculate the loss

    * Compute gradients w.r.t the weights and biases

    * Adjust the weights by subtracting a small quantity proportional to the gradient

    * Reset the gradients to zero
    
    

In [77]:
# calculate loss
loss = mse(preds, targets)
print (loss)

tensor(622.9136, grad_fn=<DivBackward0>)


In [78]:
# compute gradients
loss.backward()
print (w.grad)
print (b.grad)

tensor([[ 1868.4410,  2174.0151,  1367.3108],
        [-1070.1625,  -316.3842,  -463.9043]])
tensor([ 22.9843, -11.2035])


In [79]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [80]:
print (w, b)

tensor([[-0.5803,  0.8483,  1.3191],
        [-0.8310,  1.6275,  0.2209]], requires_grad=True) tensor([-0.3907,  1.0252], requires_grad=True)


In [81]:
# calculating loss
preds = model(inputs)
loss  = mse(preds, targets)
print (loss)

tensor(517.4789, grad_fn=<DivBackward0>)


In [82]:
# training for multiple epochs

for i in range(100):
    preds = model(inputs)
    loss  = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
    

In [83]:
preds = model(inputs)
loss  = mse(preds, targets)
print (loss)

tensor(112.5866, grad_fn=<DivBackward0>)


In [84]:
print (preds
      )

tensor([[ 55.8683,  67.3889],
        [ 85.4439,  92.7072],
        [113.4147, 155.7666],
        [ 14.3398,  18.4401],
        [111.4086, 116.3273]], grad_fn=<AddBackward0>)


In [85]:
print (targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
